import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "JungEun.log",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <head>
        <link rel="icon" href="/images/logo.png" type="image/png" />
      </head>
      <body style={{ fontFamily: '"Pretendard-Regular", sans-serif' }}>
        {children}
      </body>
      </html>
  );
}
